/**
 * generated by Xtext 2.10.0
 */
package br.consiste.ui;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SysADLUiModule /* implements AbstractSysADLUiModule  */{
  @Override
  public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
    return IXtextEditorCallback.NullImpl.class;
  }
}
