/**
 * generated by Xtext 2.12.0
 */
package br.consiste.ide;

import br.consiste.SysADLStandaloneSetup;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SysADLIdeSetup extends SysADLStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from SysADLRuntimeModule to Module"
      + "\nType mismatch: cannot convert from SysADLIdeModule to Module");
  }
}
