/**
 * generated by Xtext 2.12.0
 */
package br.consiste.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SysADLIdeModule /* implements AbstractSysADLIdeModule  */{
}
