/**
 * generated by Xtext 2.10.0
 */
package br.consiste;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SysADLStandaloneSetup /* implements SysADLStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type SysADLStandaloneSetup");
  }
}
